parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: clubA
    database_user: root
    database_password: mysql
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: cfc0ce74b843d42884d2f124f4996b62d4b158dd
    database_path: null
