parameters:
#    isra_saludo.example.class: Isra\SaludoBundle\Example

services:
#    isra_saludo.example:
#        class: %isra_saludo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
